### ISSUE TITLE
Upload pre-built HTML files as a website

### ISSUE THREAD

**Issue by kirbyfan64** [palmer-dabbelt/pconfigure#10]
It's hard to read pconfigure's docs since they have to be built locally. It would be great if you could make a pre-built version of the LaTeX docs and push it as a website. Building them is easy with `htlatex`:

```
$ htlatex pconfigure.tex
```

**Comment by palmer-dabbelt** [comment]
You can actually use

````
$ tek --with-html
````

which generates some (maybe) necessary boilerplate and then calls "mk4ht", which I've found produces slightly better output.  I keep a copy at <http://www.dabbelt.com/~palmer/software/pconfigure/doc/>, but it's frequently out of date.  I updated it today.

If you have any better suggestions as to where I should put this I'm all ears :).

**Comment by kirbyfan64** [comment]
@palmer-dabbelt You could put it on GitHub pages. Put something crazy on the home page and manually upload the HTML file for the docs.

**Comment by palmer-dabbelt** [comment]
I copied the documentation here <http://palmer-dabbelt.github.io/pconfigure/>.  It's super ugly, but at least I don't have to host it.

**Comment by palmer-dabbelt** [comment]
This appears to be working, so I'm closing the issue.

**Comment by kirbyfan64** [comment]
Maybe it should be mentioned in the README?

**Comment by palmer-dabbelt** [comment]
As of https://github.com/palmer-dabbelt/pconfigure/commit/263c051e2e44f4ddf12bc73b44433eb45c8f96d7 it is.
