### ISSUE TITLE
If I add a static library to DEPLIBS, the binary is linked to a shared version

### ISSUE THREAD

**Issue by kirbyfan64** [palmer-dabbelt/pconfigure#14]
IMO, this is completely the opposite of what one would expect.

**Comment by kirbyfan64** [comment]
Actually, I somehow managed to get pconfigure to generate an invalid dependency on a shared object that doesn't exist...

**Comment by palmer-dabbelt** [comment]
You're right, this is definitely wrong.  Can you attach the configfile that
breaks?  I'm fairly sure I have an idea of why this is broken.

**Comment by kirbyfan64** [comment]
I'm not on a computer right now, but it was something like this:

```
LANGUAGES += c
COMPILEOPTS += -Wno-parentheses

CONFIG += flags
# ^ a little configuring script
# at https://github.com/kirbyfan64/unmangler/blob/master/Configfiles/main

LIBRARIES += libregexp9.a
SOURCES += ...

BINARIES += unmangler
DEPLIBS += regexp9
SOURCES += unmangler.c
```
